### ISSUE TITLE
Exception while Upgrading three nodes kafka from version 0.10.1.1 to  2.1.0 

### ISSUE THREAD

**Issue by liqiang183** [axbaretto/kafka#4]
I want to  Upgrade three nodes kafka from version 0.10.1.1 to  2.1.0 。
Firstly，I upgrade one node to 2.10 ,and it is success .The three kafka are all avaliable.
Then,there two nodes are old version ,when i restart the old kafka ,an exception is merge.
the server.log shows
2019-04-02 09:58:10.286 GMT+08:00 FATAL Fatal error during KafkaServerStartable startup. Prepare to shutdown (kafka.server.KafkaServerStartable)
kafka.common.KafkaException: TransactionalId not a valid resourceType name. The valid names are Cluster,Topic,Group
        at kafka.security.auth.ResourceType$$anonfun$fromString$1.apply(ResourceType.scala:49)
        at kafka.security.auth.ResourceType$$anonfun$fromString$1.apply(ResourceType.scala:49)
        at scala.Option.getOrElse(Option.scala:121)
        at kafka.security.auth.ResourceType$.fromString(ResourceType.scala:49)
        at kafka.security.auth.SimpleAclAuthorizer$$anonfun$loadCache$1$$anonfun$apply$mcV$sp$1.apply(SimpleAclAuthorizer.scala:233)
        at kafka.security.auth.SimpleAclAuthorizer$$anonfun$loadCache$1$$anonfun$apply$mcV$sp$1.apply(SimpleAclAuthorizer.scala:232)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at kafka.security.auth.SimpleAclAuthorizer$$anonfun$loadCache$1.apply$mcV$sp(SimpleAclAuthorizer.scala:232)
        at kafka.security.auth.SimpleAclAuthorizer$$anonfun$loadCache$1.apply(SimpleAclAuthorizer.scala:230)
        at kafka.security.auth.SimpleAclAuthorizer$$anonfun$loadCache$1.apply(SimpleAclAuthorizer.scala:230)
        at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:234)
        at kafka.utils.CoreUtils$.inWriteLock(CoreUtils.scala:242)
        at kafka.security.auth.SimpleAclAuthorizer.loadCache(SimpleAclAuthorizer.scala:230)
        at kafka.security.auth.SimpleAclAuthorizer.configure(SimpleAclAuthorizer.scala:115)
        at kafka.server.KafkaServer$$anonfun$startup$4.apply(KafkaServer.scala:239)
        at kafka.server.KafkaServer$$anonfun$startup$4.apply(KafkaServer.scala:237)
        at scala.Option.map(Option.scala:146)
        at kafka.server.KafkaServer.startup(KafkaServer.scala:237)
        at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:39)
        at kafka.Kafka$.main(Kafka.scala:67)
        at kafka.Kafka.main(Kafka.scala)

 when i upgrade the libs in old kafka ,and the it start succcessfuly,And no error.
But,when upgrading is failed ,i want to rollback .With this exception ,i can not rollback .because old kafka can not starts,if there is new kafka in colony。

so i ask you for help   .
Thanks

**Comment by xutingz** [comment]
not sure if this problem got resolved. But for us, the workaround is to manually clean up zk and remove the "TransactionalId" and 'DelegationToken' for the old broker restart to work.
